### ISSUE TITLE
[BUG] Cannot destructure property 'id' of 't.getters.player/track' as it is undefined.

### ISSUE THREAD

**Issue by DtxdF** [tamland/airsonic-refix#128]
Hi,

When removing the last track in the `Playing` section the following errors appear in Vivaldi (Desktop & Mobile):

```text
Cannot destructure property 'id' of 't.getters.player/track' as it is undefined.
TypeError: Cannot destructure property 'id' of 't.getters.player/track' as it is undefined. at ro.<anonymous> (http://airsonic-refix.centralita.lan/js/app.80ba8a60.js:1:98843) at Vn (http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:24712) at t.run (http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:29147) at Xr (http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:34242) at Array.<anonymous> (http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:25805) at Gn (http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:25200)
```

In Firefox is a bit different:

```text
t.getters['player/track'] is undefined
614/Ao/<@http://airsonic-refix.centralita.lan/js/app.80ba8a60.js:1:98857 Vn@http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:24712 144/t.prototype.run@http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:29149 Xr@http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:34242 144/Xn/<@http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:25805 Gn@http://airsonic-refix.centralita.lan/js/chunk-vendors.c686e27d.js:62:25200 
```

Even if this error appears, the track is removed anyway.

Tested on:

| Browser | Operating System |
| --- | --- |
| Vivaldi Browser 6.4.3171.110 | Android 8.0.0 |
| Vivaldi Browser 6.4.3160.47 | Windows 10 |
| Firefox 120.0 | FreeBSD 13.2-RELEASE |

**Comment by tamland** [comment]
Fixed
